# Generated by Django 4.2 on 2023-04-19 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_from_user', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=2000)),
                ('long_name', models.CharField(blank=True, max_length=300)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('image_name', models.CharField(blank=True, max_length=100)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_tracker.catagory')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_tracker.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='Price Date')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_tracker.part')),
            ],
        ),
    ]
