# Generated by Django 4.2 on 2023-04-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('catagory', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=100)),
                ('image_location', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('retailer', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=2000)),
            ],
        ),
    ]
