# Generated by Django 4.2 on 2023-04-14 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('part_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='price date'),
            preserve_default=False,
        ),
    ]
