# Generated by Django 4.2 on 2023-04-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='part_number',
        ),
    ]
