# Generated by Django 4.2 on 2023-04-15 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_tracker', '0002_remove_version_part_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='catagory',
        ),
        migrations.AddField(
            model_name='version',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='part_tracker.catagory'),
            preserve_default=False,
        ),
    ]
