# Generated by Django 4.2 on 2023-04-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_tracker', '0002_rename_image_name_part_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
