# Generated by Django 4.2 on 2023-04-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_tracker', '0002_part_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='Price Date')),
                ('retailer', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=2000)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_tracker.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=100)),
                ('image_location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.AddField(
            model_name='component',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_tracker.version'),
        ),
    ]
