# Generated by Django 4.2 on 2023-04-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_tracker', '0003_catagory_component_version_delete_part_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='image_location',
            new_name='image_name',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='number',
            new_name='part_number',
        ),
    ]
