# Generated by Django 4.2 on 2023-04-15 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_tracker', '0003_remove_component_catagory_version_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Version',
            new_name='Model',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='version',
            new_name='model',
        ),
    ]
