# Generated by Django 4.2 on 2023-04-16 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_tracker', '0004_rename_version_model_rename_version_component_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component',
            new_name='MerchantPart',
        ),
    ]
