# Generated by Django 4.2 on 2023-04-16 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_tracker', '0005_rename_component_merchantpart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantpart',
            name='date',
        ),
        migrations.RemoveField(
            model_name='merchantpart',
            name='price',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='Price Date')),
                ('merchant_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_tracker.merchantpart')),
            ],
        ),
    ]
