# Generated by Django 4.2 on 2023-04-16 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_tracker', '0006_remove_merchantpart_date_remove_merchantpart_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='PartModel',
        ),
    ]
