# Generated by Django 4.2 on 2023-04-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_tracker', '0007_rename_model_partmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmodel',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partmodel',
            name='long_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
